language: generic

services:
    - docker
script:
    - docker-compose run client sh -c "CI=true npm run test -- --coverage"
after_success:
    - docker build -t amaurycdr/multi-client ./client
    - docker build -t amaurycdr/multi-nginx ./nginx
    - docker build -t amaurycdr/multi-server ./server
    - docker build -t amaurycdr/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push amaurycdr/multi-client
    - docker push amaurycdr/multi-nginx
    - docker push amaurycdr/multi-server
    - docker push amaurycdr/multi-worker

deploy:
    provider: elasticbeanstalk
    region: 'us-east-2'
    app: 'multi-docker'
    env: 'MultiDocker-env-1'
    bucket_name: 'elasticbeanstalk-us-east-2-253036311115'
    bucket_path: 'docker-multi'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
